config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "brains#index"

  resources :brains do
    resources :bookings, only: [:new, :create, :index]
  end

  # Define a custom route for my_bookings action outside the resources :brains block
  resources :bookings, only: [:show, :destroy, :edit]

  get 'my_bookings', to: "bookings#my_bookings"
  get 'active_bookings', to: 'bookings#active_bookings'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :brain
  belongs_to :user

  validates :length_of_time, presence: true
  validates :start_date, presence: true
  validates :status, presence: true
end

app/models/brain.rb
class Brain < ApplicationRecord
  belongs_to :user

  has_many :bookings, dependent: :destroy
  has_many :renting_users, through: :bookings, source: :user


  validates :name, presence: true
  validates :characteristics, presence: true
  validates :description, presence: true
  validates :specialities, presence: true
  validates :available, inclusion: { in: [true, false] }
  validates :location, presence: true
  has_one_attached :photo

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :owned_brain, class_name: 'Brain', dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :rented_brains, through: :bookings, source: :brain

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :destroy, :edit, :update]

  def index
    @bookings = current_user.bookings.where(status: 'active')
  end

  def new
    @booking = Booking.new
    @brain = Brain.find(params[:brain_id])
  end

  def create
    @brain = Brain.find(params[:brain_id])

    if @brain.user_id == current_user.id
      redirect_to @brain, alert: "You cannot book your own brain."
      return
    end

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.brain = @brain
    @booking.status = "Pending"

    if booking_conflict?
      render :new, notice: "You are not authorized to delete this brain."
    elsif @booking.save
      redirect_to booking_path(@booking), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def show
  end

  def my_bookings
    @bookings = current_user.bookings
    @my_brain = current_user.owned_brain
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path, notice: 'Booking was successfully destroyed.'
  end

  def edit
    @brain = @booking.brain
  end

  def update
    if @booking.update(booking_params)
      redirect_to brains_path(@brain), notice: 'Booking status updated successfully.'
    else
      render :edit
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:brain_id, :start_date, :length_of_time, :status)
  end

  def booking_conflict?
    existing_bookings = @brain.bookings.where("start_date <= ? AND (start_date + interval '1 day' * length_of_time) > ?", @booking.start_date, @booking.start_date)
    existing_bookings.exists?
  end
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  def index
    @brains = Brain.all
    if user_signed_in?
      @my_brain = current_user.owned_brain
      @booking = @my_brain&.bookings&.find_by(status: 'active') if @my_brain
    end
    @available_brains = Brain.where(available: true)

    @markers = @brains.geocoded.map do |brain|
      {
        lat: brain.latitude,
        lng: brain.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {brain: brain}),
        marker_html: render_to_string(partial: "marker", locals: {brain: brain})
      }
    end
  end

  def show
    @bookings = @brain.bookings.all
  end

  def new
    if current_user.owned_brain
      redirect_to current_user.owned_brain, alert: 'You can only create one brain.'
    else
      @brain = Brain.new
    end
  end

  def create
    @brain = Brain.new(brain_params)
    @brain.user = current_user

    if @brain.save
      redirect_to @brain, notice: 'Brain was successfully created.'
    else
      render :new
    end
  end

  def edit
    unless @brain.user == current_user
      redirect_to @brain, alert: "You are not authorized to edit this brain."
    end
  end

  def update
    if @brain.update(brain_params)
      redirect_to @brain, notice: 'Brain was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @brain.user == current_user
      @brain.destroy
      redirect_to brains_url, notice: 'Brain was successfully destroyed.'
    else
      redirect_to @brain, alert: "You are not authorized to delete this brain."
    end
  end

  private

  def set_brain
    @brain = Brain.find(params[:id])
  end

  def brain_params
    params.require(:brain).permit(:name, :characteristics, :description, :specialities, :location, :available, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-container">
  <%= form_with(model: [@brain, @booking], local: true) do |form| %>

    <div class="field">
      <%= form.label :start_date %>
      <%= form.date_field :start_date, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :length_of_time %>
      <%= form.number_field :length_of_time, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Create a booking', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/bookings/edit.html.erb
<h1>Edit Booking for <%= @brain.name %></h1>

<%= render 'form' %>

<%= link_to "Back to Your Bookings", my_bookings_path %>

app/views/bookings/index.html.erb
<div class="page">
  <h1>Your Bookings</h1>

  <% if @bookings.any? %>
    <ul>
      <% @bookings.each do |booking| %>
        <li>
          <%= link_to "#{booking.brain.name} - #{booking.start_date}", booking_path(booking) %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>You have no bookings.</p>
  <% end %>

  <%= link_to "Book a brain", brains_path, class: "btn-link" %>
</div>

app/views/bookings/my_bookings.html.erb
<!-- app/views/bookings/index.html.erb -->
<div class="page">
  <h1>Your Bookings</h1>

  <% if @bookings.any? %>
    <ul>
      <% @bookings.each do |booking| %>
        <li>
          <%= link_to "#{booking.brain.name} - #{booking.start_date}", booking_path(booking) %> <%= "#{booking.status}" %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>You have no bookings.</p>
  <% end %>

<div class="my-brain-status">
  <h1>My Brain Status:</h1>
  <% if @my_brain %>
    <ul>
      <li> Brain Name: <%= @my_brain.name %></li>
      <% if @my_brain.bookings.any? %>
        <li>Has someone booked my brain? Yes</li>
      <% else %>
        <li>Has someone booked my brain? No</li>
      <% end %>
      <li><%= link_to "Show My Brain", brain_path(@my_brain), class: 'btn button-link' %></li>
    </ul>
  <% else %>
    <p>You have not created a brain yet.</p>
  <% end %>
</div>
  <%= link_to "Back", brains_path, class: 'btn button-link' %>
</div>

app/views/bookings/new.html.erb
<div class="booking-container">
<h1 class="booking-heading"> New Booking for <%= @brain.name %></h1>

<%= render 'form' %>

  <div class="booking-actions">
<%= link_to "My Booked Brains", my_bookings_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p><strong>Brain:</strong> <%= @booking.brain.name %></p>
<p><strong>Characteristics:</strong> <%= @booking.brain.characteristics %></p>
<p><strong>Description:</strong> <%= @booking.brain.description %></p>
<p><strong>Specialities:</strong> <%= @booking.brain.specialities %></p>
<p><strong>Length of Time:</strong> <%= @booking.length_of_time %> days</p>
<p><strong>Start Date:</strong> <%= @booking.start_date %></p>
<p><strong>Status:</strong> <%= @booking.status %></p>
<% if @booking.status == 'Accepted' && Date.today < @booking.start_date %>
  <p>Your booked brain will be available to you on the <%= @booking.start_date %> for <%= @booking.length_of_time %> days.</p>
<% end %>
<% if @booking.status == 'Accepted' && Date.today >= @booking.start_date && Date.today <= (@booking.start_date + @booking.length_of_time.days) %>
  <p>Your booked brain is now available to use.</p>
  <p>Ask your booked brain a question.</p>
  <%= simple_form_for @booking, url: booking_path(@booking), method: :patch do |f| %>
    <%= f.simple_fields_for :brain do |bf| %>
      <div class="field">
        <%= bf.input :question %>
        <%= bf.button :submit, 'Submit', class: 'btn btn-primary', data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  <% end %>
<% end %>

<% if @booking.brain.answer.present? %>
  <p>Here is your booked brain's response:</p>
  <p><%= @booking.brain.answer %></p>
<% end %>

<%= link_to "Edit Booking", edit_booking_path(@booking) %>
<%= link_to "Delete Booking", booking_path(@booking), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
<%= link_to "Back to Your Bookings", my_bookings_path %>

app/views/brains/_form.html.erb
<%= form_with(model: @brain, local: true) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :characteristics %>
    <%= form.text_area :characteristics %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :specialities %>
    <%= form.text_area :specialities %>
  </div>

    <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

<div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brains/_info_window.html.erb
<h2><%= brain.name %></h2>
<p><%= brain.location %></p>

app/views/brains/_marker.html.erb
<%= link_to brain_path(brain) do %>
 <%= image_tag "brain.jpg", height: 30, width: 30, alt: "brain" %>
<% end %>

app/views/brains/aplication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrainStorm</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= yield %>
      <%= render "shared/flashes" %>
    </div>
  </body>
</html>

app/views/brains/edit.html.erb
<div class="container">
  <h1>Edit Brain</h1>

  <%= render 'form' %>

  <%= link_to "Cancel", brain_path(@brain), class: "cancel-link" %>
</div>

app/views/brains/home.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Home Page</title>
  <%= stylesheet_link_tag 'home' %>
</head>
<body>
  <header>
    <h1>Welcome to the Brain Booking App</h1>
  </header>
  <div class="container">
    <main>
      <h2>About Our Service</h2>
      <p>We offer a unique service to book brains for various purposes. Explore our offerings and find the perfect brain for your needs.</p>
      <%= link_to 'Book Now', new_brain_booking_path, class: 'btn btn-primary' %>
      <%= link_to 'Learn More', about_path, class: 'btn btn-secondary' %>
    </main>
  </div>
  <footer>
    <p>&copy; 2024 Brain Booking App. All rights reserved.</p>
  </footer>
</body>
</html>

app/views/brains/index.html.erb
<div class="page">
  <% if user_signed_in? %>
    <h2> Hi <%= current_user.first_name %> <%= current_user.last_name %> </h2>
    <p> Welcome to BrainStorm, your premium brain renting locale </p>
  <% else %>
    <p> Welcome to BrainStorm, your premium brain renting locale </p>
  <% end %>



  <h2>Book a Brain:</h2>
  <% if @brains.any? %>
    <div class="cards-container">
      <% @brains.each do |brain| %>
        <div class="card-product">
        <% if brain.photo.attached?%>
            <%= cl_image_tag brain.photo.key, height: 300, width: 400, crop: :fill %>
         <% end %>
          <div class="card-product-infos">
           <h2><%= link_to brain.name, brain_path(brain)%></h2>
          <p><strong>Status:</strong>
            <% if brain.available %>
              Available
            <% else %>
              Not Available
            <% end %>
          </p>
        <p> <%=brain.description%></p>
        </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p> There are no brains available to be booked. </p>
  <% end %>

  <div class="map-container"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<div class="logout-container">
  <%= link_to "Log out", destroy_user_session_path, class: 'logout-link', data: { turbo_method: :delete } %>
</div>

app/views/brains/new.html.erb
<div class="center-container">
  <h1 class="booking-heading">New Brain <%= @brain.name %></h1>
</div>

<%= render 'form' %>

<div class="booking-actions">
  <%= link_to "My Booked Brains", my_bookings_path, class: 'btn btn-primary' %>
</div>

app/views/brains/show.html.erb
<div class="page">
<div class="d-flex">
  <h1><%= @brain.name %></h1>
   <%= link_to 'Edit Brain', edit_brain_path(@brain), class: 'btn btn-primary' %>
    <%= link_to 'Delete Brain', brain_path(@brain), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
</div>
  <p><strong>Characteristics:</strong> <%= @brain.characteristics %></p>
  <p><strong>Description:</strong> <%= @brain.description %></p>
  <p><strong>Specialities:</strong> <%= @brain.specialities %></p>
  <p><strong>Current availability:</strong> <%= @brain.available ? 'Available' : 'Not Available' %></p>
  <%= cl_image_tag @brain.photo.key, height: 300, width: 400, crop: :fill %>
  <% if user_signed_in? && @brain.user_id == current_user.id %>

  <h2>Bookings for this Brain</h2>
    <% if @bookings.any? %>
      <ul>
        <% @bookings.each do |booking| %>
          <li>
            <strong>User:</strong> <%= booking.user.email %><br>
            <strong>Start Date:</strong> <%= booking.start_date %><br>
            <strong>Length of Time:</strong> <%= booking.length_of_time %> days<br>
            <strong>Status:</strong> <%= booking.status %>
            <%= simple_form_for booking do |f| %>
              <%= f.hidden_field :status, value: 'Accepted' %>
              <%= f.button :submit, 'Accept', class: 'btn btn-primary', data: { confirm: 'Are you sure?' } %>
              <% end %>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p>No bookings have been made for this brain yet.</p>
    <% end %>
  <% end %>
  <% if user_signed_in? && @brain.user_id != current_user.id %>
    <%= link_to "Book this brain", new_brain_booking_path(@brain), class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Back to Brains List', brains_path, class: 'btn btn-secondary' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrainStorm</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/about.html.erb
<h2> This is our about brain page </h2>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://www.verywellmind.com/thmb/C9O-tyeU39g-N-d1w2w32RJ1hCc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/human-brain-regions--illustration-713784787-5973a8a8d963ac00103468ba.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add a Brain", new_brain_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Bookings", my_bookings_path, class: "nav-link" %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>